project '../CambrianDemo.xcodeproj'
workspace 'CambrianDemo.xcworkspace'

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

abstract_target 'defaults' do

  source 'https://github.com/CocoaPods/Specs.git'

  pod 'JGProgressHUD'
  pod 'RealmSwift'
  pod 'Kingfisher'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '3.2'
          end
      end
  end

  target 'CambrianDemo'

end